import {useEffect,useMemo,useState} from "react";
import {onAuthStateChanged,signInWithEmailAndPassword,signOut,User} from "firebase/auth";
import {addDoc,collection,onSnapshot,serverTimestamp} from "firebase/firestore";
import ExcelJS from "exceljs";
import {Activity,BarChart3,Car,ClipboardList,Download,FileSpreadsheet,Gauge,LogOut,Menu,Wrench,X} from "lucide-react";
import {auth,db} from "./lib/firebase";

type Vehicle={id:string;prefix:string;plate:string;brand:string;model:string;year:number;mileage:number;type:string;category:string;status:string};
type OS={id:string;number:string;vehicleId:string;type:string;priority:string;status:string;openedAt:string;description:string;laborCost:number;partsCost:number;totalCost:number};

const demo:Vehicle[]=[
{id:"demo1",prefix:"FROTA-001",plate:"ABC1D23",brand:"Mercedes-Benz",model:"Accelo",year:2023,mileage:128450,type:"Caminhão",category:"Caminhão leve",status:"Disponível"},
{id:"demo2",prefix:"FROTA-002",plate:"DEF4G56",brand:"Volkswagen",model:"Delivery",year:2022,mileage:174220,type:"Guincho",category:"Guincho leve",status:"Em manutenção"},
{id:"demo3",prefix:"FROTA-003",plate:"GHI7J89",brand:"Scania",model:"P 320",year:2021,mileage:241800,type:"Guincho",category:"Guincho pesado",status:"Disponível"}];

function money(v:number){return v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function Login(){const[email,setEmail]=useState("rafael@system.com");const[pwd,setPwd]=useState("");const[err,setErr]=useState("");const[busy,setBusy]=useState(false);
async function go(e:React.FormEvent){e.preventDefault();setBusy(true);setErr("");try{await signInWithEmailAndPassword(auth,email,pwd)}catch{setErr("Login inválido. Verifique o usuário no Firebase Authentication.")}finally{setBusy(false)}}
return <div className="login"><div className="login-brand"><div className="eixo-logo"><span>EIXO</span><b>[SP]</b></div><span>GESTÃO DE FROTA</span></div><form className="login-card" onSubmit={go}><div className="eixo-logo eixo-logo-dark"><span>EIXO</span><b>[SP]</b></div><small>PPCM • PLANEJAMENTO, PROGRAMAÇÃO E CONTROLE DA MANUTENÇÃO</small><h1>Controle de manutenção</h1><p>Preventivas, corretivas, OS, custos e indicadores em um só lugar.</p><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" value={pwd} onChange={e=>setPwd(e.target.value)} /></label>{err&&<div className="error">{err}</div>}<button className="primary" disabled={busy}>{busy?"Entrando...":"Entrar"}</button><em>Acesso administrativo</em></form></div>}

function App(){
const[user,setUser]=useState<User|null>(null);const[ready,setReady]=useState(false);const[page,setPage]=useState("Dashboard");const[open,setOpen]=useState(false);const[vehicles,setVehicles]=useState<Vehicle[]>([]);const[orders,setOrders]=useState<OS[]>([]);
useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setReady(true)}),[]);
useEffect(()=>{if(!user)return;const a=onSnapshot(collection(db,"vehicles"),s=>setVehicles(s.docs.map(d=>({id:d.id,...d.data()} as Vehicle))));const b=onSnapshot(collection(db,"workOrders"),s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()} as OS))));return()=>{a();b()}},[user]);
if(!ready)return <div className="loading">Carregando...</div>;if(!user)return <Login/>;
const fleet=vehicles.length?vehicles:demo;const available=fleet.filter(v=>v.status==="Disponível").length;const openOs=orders.filter(o=>o.status!=="Encerrada").length;const cost=orders.reduce((a,o)=>a+Number(o.totalCost||0),0);
const nav=[["Dashboard",Gauge],["Frota",Car],["Preventivas",ClipboardList],["Ordens de Serviço",Wrench],["Indicadores",BarChart3],["Relatórios",FileSpreadsheet]] as const;
return <div className="shell"><aside><div className="brand"><div className="eixo-logo eixo-logo-light"><span>EIXO</span><b>[SP]</b></div><div><b>PPCM</b><small>Gestão de Frota</small></div></div><nav>{nav.map(([n,I])=><button className={page===n?"active":""} onClick={()=>setPage(n)} key={n}><I size={17}/>{n}</button>)}</nav><div className="aside-bottom"><small>{user.email}</small><button onClick={()=>signOut(auth)}><LogOut size={17}/>Sair</button></div></aside><main><header><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><b>{page}</b><small>PPCM • Controle de manutenção</small></div><button className="secondary" onClick={()=>exportExcel(fleet,orders)}><Download size={16}/> Excel</button></header><section className="content">
{page==="Dashboard"&&<Dashboard fleet={fleet} available={available} openOs={openOs} cost={cost} orders={orders}/>}
{page==="Frota"&&<Fleet fleet={fleet} onAdd={()=>setPage("Novo veículo")}/>}
{page==="Novo veículo"&&<VehicleForm onBack={()=>setPage("Frota")}/>}
{page==="Preventivas"&&<Preventive fleet={fleet}/>}
{page==="Ordens de Serviço"&&<Orders orders={orders} fleet={fleet} onAdd={()=>setOpen(true)}/>}
{page==="Indicadores"&&<Indicators fleet={fleet} orders={orders}/>}
{page==="Relatórios"&&<Reports fleet={fleet} orders={orders}/>}
</section>{open&&page==="Ordens de Serviço"&&<OsModal fleet={fleet} close={()=>setOpen(false)}/>}</main></div>}

function Card({icon:I,title,value,note}:{icon:any;title:string;value:any;note:string}){return <div className="card"><div className="icon"><I size={19}/></div><div><small>{title}</small><strong>{value}</strong><em>{note}</em></div></div>}
function Dashboard(p:any){return <><div className="head"><div><h2>Visão geral</h2><p>Resumo operacional da manutenção.</p></div></div><div className="cards"><Card icon={Car} title="Frota total" value={p.fleet.length} note={p.available+" disponíveis"}/><Card icon={Gauge} title="Disponibilidade" value={(p.available/p.fleet.length*100).toFixed(1)+"%"} note="disponíveis / frota"/><Card icon={Wrench} title="OS abertas" value={p.openOs} note="backlog atual"/><Card icon={BarChart3} title="Custo manutenção" value={money(p.cost)} note="OS carregadas"/></div><div className="cols"><Panel title="Status da frota">{p.fleet.map((v:Vehicle)=><Row key={v.id} left={v.prefix+" • "+v.brand+" "+v.model} right={v.status}/>)}</Panel><Panel title="Ordens recentes">{p.orders.length?p.orders.slice(0,6).map((o:OS)=><Row key={o.id} left={"OS "+o.number+" • "+o.description} right={o.status}/>):<Empty text="Nenhuma OS cadastrada."/>}</Panel></div></>}
function Panel({title,children}:any){return <div className="panel"><h3>{title}</h3>{children}</div>}
function Row({left,right}:{left:string;right:string}){return <div className="row"><span>{left}</span><b>{right}</b></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Fleet({fleet,onAdd}:{fleet:Vehicle[];onAdd:()=>void}){return <><div className="head"><div><h2>Frota</h2><p>Cadastro, classificação, quilometragem e disponibilidade.</p></div><button className="primary" onClick={onAdd}>+ Novo veículo</button></div><Table headers={["Prefixo","Placa","Veículo","Classificação","Ano","KM","Status"]}>{fleet.map(v=><tr key={v.id}><td>{v.prefix}</td><td>{v.plate}</td><td>{v.brand+" "+v.model}</td><td><span className="tag">{v.category||v.type}</span></td><td>{v.year}</td><td>{v.mileage.toLocaleString("pt-BR")}</td><td>{v.status}</td></tr>)}</Table></>}
function Table({headers,children}:any){return <div className="panel table"><table><thead><tr>{headers.map((h:string)=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function VehicleForm({onBack}:{onBack:()=>void}){const[f,setF]=useState({prefix:"",plate:"",brand:"",model:"",year:new Date().getFullYear(),mileage:0,type:"Veículo operacional",category:"Caminhão leve",status:"Disponível"});
async function save(e:React.FormEvent){e.preventDefault();await addDoc(collection(db,"vehicles"),{...f,createdAt:serverTimestamp()});onBack()}
const categories=["Passeio","Utilitário leve","Picape","Van","Caminhão leve","Caminhão médio","Caminhão pesado","Guincho leve","Guincho pesado","Caminhão-pipa","Veículo de inspeção","Veículo operacional","Outro"];
return <><div className="head"><div><h2>Novo veículo</h2><p>Cadastre o ativo e classifique-o para análises de disponibilidade, manutenção e custos.</p></div><button className="secondary" onClick={onBack}>Voltar</button></div><form className="panel form" onSubmit={save}>{["prefix","plate","brand","model","year","mileage"].map(k=><label key={k}>{k==="prefix"?"Prefixo":k==="plate"?"Placa":k==="brand"?"Marca":k==="model"?"Modelo":k==="year"?"Ano":"Quilometragem (KM)"}<input required value={(f as any)[k]} onChange={e=>setF({...f,[k]:["year","mileage"].includes(k)?Number(e.target.value):e.target.value})}/></label>)}<label>Tipo<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>Veículo leve</option><option>Veículo pesado</option><option>Guincho</option><option>Veículo operacional</option></select></label><label>Classificação<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>Disponível</option><option>Em manutenção</option><option>Indisponível</option><option>Baixado</option></select></label><button className="primary">Salvar veículo</button></form></>}
function Preventive({fleet}:{fleet:Vehicle[]}){return <><div className="head"><div><h2>Preventivas</h2><p>Planejamento por KM e tempo.</p></div></div><Panel title="Planejamento inicial"><Empty text="Cadastre os planos preventivos para controlar próxima manutenção, aderência e atrasos."/><div className="tip">Modelo recomendado: plano → veículo → intervalo KM → intervalo dias → próxima execução → status.</div></Panel></>}
function Orders({orders,fleet,onAdd}:{orders:OS[];fleet:Vehicle[];onAdd:()=>void}){return <><div className="head"><div><h2>Ordens de Serviço</h2><p>Abertura, programação, execução e encerramento.</p></div><button className="primary" onClick={onAdd}>+ Nova OS</button></div><Table headers={["OS","Veículo","Tipo","Prioridade","Status","Custo"]}>{orders.map(o=><tr key={o.id}><td>{o.number}</td><td>{fleet.find(v=>v.id===o.vehicleId)?.prefix||o.vehicleId}</td><td>{o.type}</td><td>{o.priority}</td><td>{o.status}</td><td>{money(o.totalCost)}</td></tr>)}</Table>{!orders.length&&<div className="panel"><Empty text="Nenhuma OS cadastrada."/></div>}</>}
function Indicators({fleet,orders}:{fleet:Vehicle[];orders:OS[]}){const closed=orders.filter(o=>o.status==="Encerrada");const avg=closed.length?closed.reduce((a,o)=>a+Number(o.totalCost||0),0)/closed.length:0;return <><div className="head"><div><h2>Indicadores PPCM</h2><p>KPIs para gestão e tomada de decisão.</p></div></div><div className="cards"><Card icon={Gauge} title="Disponibilidade" value={(fleet.filter(v=>v.status==="Disponível").length/fleet.length*100).toFixed(1)+"%"} note="disponíveis / frota"/><Card icon={Activity} title="MTBF" value="—" note="alimentado com histórico"/><Card icon={Wrench} title="MTTR" value="—" note="alimentado com datas OS"/><Card icon={BarChart3} title="Custo médio/OS" value={money(avg)} note="OS encerradas"/></div><Panel title="KPIs previstos"><div className="tip">Aderência preventiva • Disponibilidade • MTBF • MTTR • Custo/km • Backlog • Produtividade de oficina.</div></Panel></>}
function Reports({fleet,orders}:{fleet:Vehicle[];orders:OS[]}){return <><div className="head"><div><h2>Relatórios</h2><p>Base pronta para Excel e Power BI.</p></div><button className="primary" onClick={()=>exportExcel(fleet,orders)}><Download size={16}/> Exportar Excel</button></div><div className="cols"><Panel title="Excel PPCM"><p>Exporta Frota e Ordens de Serviço em abas estruturadas.</p></Panel><Panel title="Power BI"><p>Use o arquivo exportado como camada de análise e evolua para um modelo dimensional.</p></Panel></div></>}
function OsModal({fleet,close}:{fleet:Vehicle[];close:()=>void}){const[f,setF]=useState({number:"OS-"+Date.now().toString().slice(-6),vehicleId:fleet[0]?.id||"",type:"Preventiva",priority:"Média",status:"Aberta",openedAt:new Date().toISOString().slice(0,10),description:"",laborCost:0,partsCost:0});
async function save(e:React.FormEvent){e.preventDefault();const total=Number(f.laborCost)+Number(f.partsCost);await addDoc(collection(db,"workOrders"),{...f,totalCost:total,odometer:fleet.find(v=>v.id===f.vehicleId)?.mileage||0,createdAt:serverTimestamp()});close()}
return <div className="modal"><div className="modal-box"><div className="modal-head"><h3>Nova OS</h3><button onClick={close}><X/></button></div><form className="form" onSubmit={save}><label>Veículo<select value={f.vehicleId} onChange={e=>setF({...f,vehicleId:e.target.value})}>{fleet.map(v=><option key={v.id} value={v.id}>{v.prefix}</option>)}</select></label><label>Tipo<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>Preventiva</option><option>Corretiva</option><option>Preditiva</option><option>Inspeção</option></select></label><label>Prioridade<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></label><label>Descrição<textarea required value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Mão de obra<input type="number" value={f.laborCost} onChange={e=>setF({...f,laborCost:Number(e.target.value)})}/></label><label>Peças<input type="number" value={f.partsCost} onChange={e=>setF({...f,partsCost:Number(e.target.value)})}/></label><button className="primary">Criar OS</button></form></div></div>}
async function exportExcel(fleet:Vehicle[],orders:OS[]){const wb=new ExcelJS.Workbook();const a=wb.addWorksheet("Frota");a.columns=[{header:"Prefixo",key:"prefix"},{header:"Placa",key:"plate"},{header:"Marca",key:"brand"},{header:"Modelo",key:"model"},{header:"Tipo",key:"type"},{header:"Classificação",key:"category"},{header:"Ano",key:"year"},{header:"KM",key:"mileage"},{header:"Status",key:"status"}];fleet.forEach(v=>a.addRow(v));const b=wb.addWorksheet("Ordens de Serviço");b.columns=[{header:"OS",key:"number"},{header:"Veículo",key:"vehicleId"},{header:"Tipo",key:"type"},{header:"Prioridade",key:"priority"},{header:"Status",key:"status"},{header:"Custo",key:"totalCost"},{header:"Descrição",key:"description"}];orders.forEach(o=>b.addRow(o));a.getRow(1).font={bold:true};b.getRow(1).font={bold:true};const buf=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([buf]));const x=document.createElement("a");x.href=url;x.download="PPCM-"+new Date().toISOString().slice(0,10)+".xlsx";x.click();URL.revokeObjectURL(url)}
export default App;